config/routes.rb
Rails.application.routes.draw do

  root 'orders#index'
  resources :orders do
    resources :products
  end

end

app/models/order.rb
class Order < ActiveRecord::Base

  has_and_belongs_to_many :products

  include VouchersHelper

  def update_total
    self.subtotal = self.products.sum(:price)
    self.total = self.subtotal - self.discount
    self.save
  end

  def apply_voucher(voucher)
    self.discount += voucher['discount']
    self.save
  end

  def remove_discounts
    self.discount = 0
    self.save
  end

end

app/models/product.rb
class Product < ActiveRecord::Base

  has_and_belongs_to_many :orders

  def add_item_decrease_quantity
    self.quantity -= 1
    self.save
  end

  def remove_item_increase_quantity
    self.quantity += 1
    self.save
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  include ActionView::Helpers::NumberHelper

  def index
    @order = Order.first_or_create
    @categories = Product.all.order(category: :desc).map { |p| p.category }.uniq
    show_category = params[:category] || Product.first.category
    @products = Product.all.where(category: show_category)
    @order.update_total
    @ordered_products = @order.products.to_a
    @available_voucher = @order.prepare_voucher
  end

  def update
    order = Order.find(params[:id])
    voucher = order.prepare_voucher
    order.apply_voucher(voucher)
    redirect_to :back
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def update
    product = Product.find(params[:id])
    product.add_item_decrease_quantity
    order = Order.find(params[:order_id])
    order.products << product
    order.remove_discounts
    redirect_to :back
  end

  def destroy
    product = Product.find(params[:id])
    product.remove_item_increase_quantity
    order = Order.find(params[:order_id])
    order.remove_discounts
    order.products.delete(product)
    redirect_to :back
  end

end

app/helpers/vouchers_helper.rb
module VouchersHelper

  VOUCHER1 = { 'description' => '$5 off your order', 'discount' => 5, 'minimum_order' => 5, 'condition' => '', 'minimum_number' => 0 }
  VOUCHER2 = { 'description' => '$10 off when you spend over $50.00', 'discount' => 10, 'minimum_order' => 50, 'condition' => '', 'minimum_number' => 0 }
  VOUCHER3 = { 'description' => '$15 off when you have bought at least one footwear item and spent over $75.00', 'discount' => 15, 'minimum_order' => 75, 'condition' => 'Footwear', 'minimum_number' => 1 }

  def vouchers
    [VOUCHER1, VOUCHER2, VOUCHER3].sort_by { |voucher| voucher['discount'] }.reverse
  end

  def prepare_voucher
    return if self.discount > 0
    vouchers.each do |voucher|
      return voucher if can_apply_voucher?(voucher)
    end
  end

  def can_apply_voucher?(voucher)
    if self.products.where('category LIKE ?', "%" + voucher['condition'] + "%").length >= voucher['minimum_number']
      return true if self.subtotal > voucher['minimum_order']
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Clothes Store</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <center>
    <%= yield %>
  </center>
</body>
</html>

app/views/orders/_shoppingcart.html.erb
<div id='cart'>
  <h3>Shopping cart:</h3>
  <br>
  <% if @ordered_products.length > 0 %>
    <% @ordered_products.uniq.each do |product| %>
      <li> <%= @ordered_products.count(product) %>x <%= product.name %> <%= number_to_currency(product.price) %>
        <br>
        <%= link_to 'Remove item', order_product_path(@order, product), method: :delete %></li>
      <br>
    <% end %>
    <b>Total: <%= number_to_currency(@order.total) %></b>
    <br>
    <% if @order.discount > 0 %>
      <i>Discount: <%= number_to_currency(@order.discount) %></i>
      <br>
    <% end %>
    <% if @available_voucher %>
      <h4>Available voucher:</h4>
      <br>
      <%= form_for [@order] do |f| %>
        <%= f.submit @available_voucher['description'] %>
      <% end %>
      <br>
    <% end %>
  <% else %>
    Empty!
  <% end %>
</div>

app/views/orders/index.html.erb
<header>
  <%= render 'partials/breadcrumbs' %>
</header>
<body>
  <div class="row">
    <div class="col-md-6"><%= render 'partials/shoppingcart' %></div>
    <div class="col-md-6"><%= render 'partials/products' %></div>
  </div>
</body>

app/views/partials/_breadcrumbs.html.erb
<ol class="breadcrumb">
  <% @categories.each do |category| %>
    <li class='category'><a href="/?category=<%= category%>"><%= category %></a></li>
  <% end %>
</ol>

app/views/partials/_products.html.erb
<div id='product-list'>
  <h3><%= @products.first.category %></h3>

  <% @products.each do |product| %>
    <b><%= product.name %></b>
    <br>
    <% if product.old_price %>
      Was <strike><%= number_to_currency(product.old_price) %></strike>
      Now
    <% end %>
    <%= number_to_currency(product.price) %>
    <br>
    <% if product.quantity < 1 %>
    <br>
      Out of Stock
    <% else %>
    <br>
      <%= form_for [@order, product] do |f| %>
        <%= f.submit 'Add to cart' %>
      <% end %>
    <% end %>
    <br>
    <br>
  <% end %>
</div>

app/views/partials/_shoppingcart.html.erb
<div id='cart'>
  <h3>Shopping cart:</h3>
  <br>
  <% if @ordered_products.length > 0 %>
    <% @ordered_products.uniq.each do |product| %>
      <li> <h5><%= @ordered_products.count(product) %>x <%= product.name %> <%= number_to_currency(product.price) %></h5>
        <%= link_to 'Remove item', order_product_path(@order, product), method: :delete %></li>
      <br>
    <% end %>
    <b>Total: <%= number_to_currency(@order.total) %></b>
    <br>
    <% if @order.discount > 0 %>
      <i>Discount: <%= number_to_currency(@order.discount) %></i>
      <br>
    <% end %>
    <% if @available_voucher %>
      <h4>Available voucher:</h4>
      <br>
      <%= form_for [@order] do |f| %>
        <%= f.submit @available_voucher['description'] %>
      <% end %>
      <br>
    <% end %>
  <% else %>
    Empty!
  <% end %>
</div>